const IPC_MAIN_EVENTS = Object.freeze({
  MAIN_LOG: "MAIN_LOG",
  MAIN_APP_RELOAD: "MAIN_APP_RELOAD",
  MAIN_APP_REFRESH: "MAIN_APP_REFRESH",
  MAIN_APP_RESET: "MAIN_APP_RESET",
});

export default IPC_MAIN_EVENTS;
