const IPC_RENDERER_EVENTS = Object.freeze({
  WEB_LOG: "WEB_LOG",
  WEB_ONLINE: "WEB_ONLINE",
  WEB_OFFLINE: "WEB_OFFLINE",
  WEB_CUSTOM_EVENT: "WEB_CUSTOM_EVENT",
  WEB_SET_COOKIE: "WEB_SET_COOKIE",
});

export default IPC_RENDERER_EVENTS;
